version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Karan@123"
      POSTGRES_DB: task_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task-tracker-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:Karan%40123@postgres:5432/task_tracker?schema=public
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://backend:3001
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=http://localhost:3001

volumes:
  postgres_data:
  backend_uploads:
